/**
 * The sound pack, synthesised from scratch.
 *
 * Every sound here is generated by this file, so there is no library licence to
 * honour and nothing that can be claimed on an upload. That matters more than
 * it sounds: a free sample pack usually forbids redistribution inside a video,
 * and an automated content match does not care whether you read the terms.
 *
 * The palette follows the video. The signature sound is a spike - a short
 * bright blip, which is literally what the thing on screen is doing - and the
 * transitions are air rather than swishes, so they sit under a music bed
 * instead of fighting it. Levels are deliberately low: the music track is left
 * empty for a song from the TikTok gallery, and these have to survive under it
 * without pushing the whole mix into a limiter.
 *
 *   node tools/sfx.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const RATE = 48000;
const OUT = (process.env.VIDEO_DIR || './video') + '/sfx';

/* ------------------------------------------------------------- primitives --- */

const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);
/** Smooth 0..1 ramp, used for every envelope so nothing clicks on its edges. */
const smooth = (p) => {
  const t = clamp(p, 0, 1);
  return t * t * (3 - 2 * t);
};
/** Bell: silent at both ends, open in the middle. */
const bell = (p, skew = 0.5) => (p < skew
  ? smooth(p / skew)
  : smooth((1 - p) / (1 - skew)));
/** Exponential decay, in seconds. */
const decay = (t, tau) => Math.exp(-t / tau);

/** One-pole low pass. `cut` in Hz, per sample. */
function makeLP() {
  let z = 0;
  return (x, cut) => {
    const a = 1 - Math.exp(-2 * Math.PI * clamp(cut, 20, RATE / 2.2) / RATE);
    z += a * (x - z);
    return z;
  };
}
/** One-pole high pass, as the complement of the same filter. */
function makeHP() {
  const lp = makeLP();
  return (x, cut) => x - lp(x, cut);
}

/**
 * A sine whose frequency is read per sample, integrating phase rather than
 * evaluating sin(2*pi*f*t) - otherwise a sweeping frequency makes the phase
 * jump and you hear it as a rasp.
 */
function makeOsc() {
  let phase = 0;
  return (freq) => {
    phase += (2 * Math.PI * freq) / RATE;
    if (phase > 2 * Math.PI) phase -= 2 * Math.PI;
    return Math.sin(phase);
  };
}

const noise = () => Math.random() * 2 - 1;

/** Gentle saturation, so a peak rounds over instead of clipping square. */
const soft = (x) => Math.tanh(x * 1.2) / Math.tanh(1.2);

/* ----------------------------------------------------------------- render --- */

/**
 * @param seconds length
 * @param peak    target peak, linear (0.25 is about -12 dBFS)
 * @param fn      (t, p, i) -> sample or [left, right]
 */
function render(seconds, peak, fn) {
  const n = Math.round(seconds * RATE);
  const L = new Float64Array(n);
  const R = new Float64Array(n);
  for (let i = 0; i < n; i++) {
    const t = i / RATE;
    const out = fn(t, i / n, i);
    if (Array.isArray(out)) { L[i] = out[0]; R[i] = out[1]; }
    else { L[i] = out; R[i] = out; }
  }
  // a short fade at both ends: a waveform that starts at a non-zero sample
  // clicks, and every editor will butt these up against something
  const edge = Math.min(Math.round(0.004 * RATE), Math.floor(n / 2));
  for (let i = 0; i < edge; i++) {
    const g = i / edge;
    L[i] *= g; R[i] *= g;
    L[n - 1 - i] *= g; R[n - 1 - i] *= g;
  }
  let max = 0;
  for (let i = 0; i < n; i++) {
    max = Math.max(max, Math.abs(L[i]), Math.abs(R[i]));
  }
  const gain = max > 0 ? peak / max : 0;
  const buf = Buffer.alloc(44 + n * 4);
  buf.write('RIFF', 0);
  buf.writeUInt32LE(36 + n * 4, 4);
  buf.write('WAVE', 8);
  buf.write('fmt ', 12);
  buf.writeUInt32LE(16, 16);
  buf.writeUInt16LE(1, 20);            // PCM
  buf.writeUInt16LE(2, 22);            // stereo
  buf.writeUInt32LE(RATE, 24);
  buf.writeUInt32LE(RATE * 4, 28);     // byte rate
  buf.writeUInt16LE(4, 32);            // block align
  buf.writeUInt16LE(16, 34);
  buf.write('data', 36);
  buf.writeUInt32LE(n * 4, 40);
  for (let i = 0; i < n; i++) {
    buf.writeInt16LE(Math.round(clamp(L[i] * gain, -1, 1) * 32767), 44 + i * 4);
    buf.writeInt16LE(Math.round(clamp(R[i] * gain, -1, 1) * 32767), 46 + i * 4);
  }
  return buf;
}

/* ------------------------------------------------------------------ pack --- */

const PACK = {
  /** Standard scene change. Air moving, not a cartoon swish. */
  'whoosh_soft': () => {
    const hp = makeHP(), lp = makeLP(), hp2 = makeHP(), lp2 = makeLP();
    return render(0.5, 0.30, (t, p) => {
      const cut = 300 + Math.pow(p, 0.7) * 5200;
      const env = bell(p, 0.42);
      const l = lp(hp(noise(), cut), cut * 2.6) * env;
      const r = lp2(hp2(noise(), cut * 1.08), cut * 2.4) * env;
      return [l, r];
    });
  },

  /** Faster and brighter, for a cut that lands on a hard fact. */
  'whoosh_hard': () => {
    const hp = makeHP(), lp = makeLP(), hp2 = makeHP(), lp2 = makeLP();
    return render(0.34, 0.38, (t, p) => {
      const cut = 700 + Math.pow(p, 0.55) * 8000;
      const env = bell(p, 0.3) * (1 - p * 0.25);
      return [lp(hp(noise(), cut), cut * 3) * env,
        lp2(hp2(noise(), cut * 1.12), cut * 2.8) * env];
    });
  },

  /** A neuron firing. The signature sound of the whole video. */
  'spike': () => {
    const osc = makeOsc(), hp = makeHP();
    return render(0.1, 0.34, (t) => {
      const body = osc(2100 - t * 4000) * decay(t, 0.012);
      const click = hp(noise(), 3000) * decay(t, 0.0025) * 0.6;
      return soft(body + click);
    });
  },

  /** A handful of them, for a brain that is busy. */
  'spike_burst': () => {
    const oscs = [], hp = makeHP();
    const times = [0, 0.045, 0.082, 0.16, 0.205, 0.29, 0.335, 0.41, 0.52, 0.6];
    for (let i = 0; i < times.length; i++) oscs.push(makeOsc());
    return render(0.75, 0.30, (t) => {
      let s = 0;
      for (let i = 0; i < times.length; i++) {
        const dt = t - times[i];
        if (dt < 0) { oscs[i](0); continue; }
        const f = 1500 + (i % 4) * 420;
        s += oscs[i](f - dt * 3000) * decay(dt, 0.011) * (0.7 + (i % 3) * 0.15);
      }
      return soft(s * 0.5 + hp(noise(), 4000) * 0.03);
    });
  },

  /** Tension before a reveal. Runs under the outgoing shot. */
  'riser': () => {
    const osc = makeOsc(), hp = makeHP(), lp = makeLP();
    return render(1.8, 0.30, (t, p) => {
      const k = Math.pow(p, 1.6);
      const tone = osc(180 + k * 1500) * 0.5;
      const air = lp(hp(noise(), 400 + k * 4000), 9000) * 0.7;
      const env = smooth(p * 1.25) * (p > 0.94 ? smooth((1 - p) / 0.06) : 1);
      return soft((tone + air) * env * 0.8);
    });
  },

  /** Lands the cut a riser was building to. */
  'impact_low': () => {
    const osc = makeOsc(), lp = makeLP(), hp = makeHP();
    return render(0.8, 0.44, (t) => {
      const body = osc(90 * Math.exp(-t * 6) + 38) * decay(t, 0.17);
      const knock = lp(noise(), 900) * decay(t, 0.02) * 0.5;
      const air = hp(noise(), 6000) * decay(t, 0.008) * 0.25;
      return soft(body * 1.1 + knock + air);
    });
  },

  /** The blade sweeping through the brain. Long, so it can be trimmed. */
  'scan_sweep': () => {
    const osc = makeOsc(), osc2 = makeOsc(), hp = makeHP(), lp = makeLP();
    return render(3.2, 0.24, (t, p) => {
      const f = 260 * Math.pow(22, p);
      const tone = (osc(f) * 0.6 + osc2(f * 1.5) * 0.25);
      const air = lp(hp(noise(), 600 + p * 3000), 8000) * 0.35;
      const env = bell(p, 0.55);
      return soft((tone + air) * env * 0.7);
    });
  },

  /** A number or a line of text arriving. */
  'tick': () => {
    const osc = makeOsc(), hp = makeHP();
    return render(0.06, 0.22, (t) => soft(
      osc(1750) * decay(t, 0.006) + hp(noise(), 5000) * decay(t, 0.002) * 0.5));
  },

  /** One dot in a grid of five hundred. */
  'pop': () => {
    const osc = makeOsc();
    return render(0.14, 0.26, (t) => soft(
      osc(900 - t * 1800) * decay(t, 0.02) * 1.2));
  },

  /** Two-tone confirm: the fly is on target and grabs. */
  'ui_confirm': () => {
    const a = makeOsc(), b = makeOsc();
    return render(0.3, 0.26, (t) => soft(
      a(880) * decay(t, 0.05) * (t < 0.08 ? 1 : 0)
      + b(1320) * decay(Math.max(0, t - 0.08), 0.07) * (t >= 0.08 ? 1 : 0)));
  },

  /** The last frame. Everything falls away. */
  'sub_drop': () => {
    const osc = makeOsc(), lp = makeLP();
    return render(1.6, 0.46, (t, p) => {
      const f = 140 * Math.exp(-t * 2.1) + 27;
      const body = osc(f) * (1 - smooth(Math.max(0, (p - 0.55) / 0.45)) * 0.9);
      const rumble = lp(noise(), 90) * 0.35 * (1 - p);
      return soft(body * 1.15 + rumble);
    });
  },
};

mkdirSync(OUT, { recursive: true });
for (const [name, make] of Object.entries(PACK)) {
  const buf = make();
  writeFileSync(join(OUT, name + '.wav'), buf);
  console.log('  ' + name + '.wav  ' + (buf.length / (RATE * 4)).toFixed(2) + 's');
}
console.log('\n-> ' + OUT);
